### ISSUE TITLE
Matrix vector multiply with mixed integer widths

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/lib_xs3_math#1]
Matrix * vector with 8-bit matrix values, 16-bit vector values and 32-bit values in the output vector.

**Comment by astewart-xmos** [comment]
This is implemented in PR #37.  Several additional low-level functions were added in support of this, including an 8-bit matrix-vector multiply-accumulate, functions to extract the high and low bytes of a 16-bit vector, and a function to determine the negative elements of an 8-bit vector.

The function to multiply an 8-bit matrix by a 16-bit vector for a 32-bit result was called `xs3_mat_mul_s8_x_s16_yield_s32()`. It has the limitation that the matrix must have a multiple of 16 rows and a multiple of 32 columns. The result is exact, so long as saturation does not occur.

The logic is:  
A 16 bit value `0xWXYZ` is the same as  `(((int32)0xWX) << 8) + 0xYZ` where `0xWX` is a signed 8-bit value and `0xYZ` is an unsigned 8-bit value.  Then the distributive property can be applied to multiply a 16-bit value by the 8-bit values from the weights. So we can reduce the mixed 8-/16-bit matrix multiplication to two 8-bit matrix-vector multiplications where one is shifted up 8 bits and then they're added together.
The remaining problem is that `0xYZ` is supposed to be unsigned, but the VPU doesn't do unsigned multiplications. This can be corrected for given that when `((int8_t)0xYZ)` is positive `((int8_t)0xYZ) == ((uint8_t)0xYZ)`, and when `((int8_t)0xYZ)` is negative,   `((int8_t)0xYZ) == (((uint8_t)0xYZ) - 256)`. By noting whether each `0xYZ` (i.e. the low byte of each element of the 16-bit vector) is negative, we can then do a correction pass which corrects for the sign error.
