### ISSUE TITLE
New functions for float FFT and vector operations

### ISSUE THREAD

**Issue by lucianomartin** [xmos/lib_xs3_math#86]
We would like to add some functions to lib_xs3_math. They have been implemented in lib_dsp. 

The functions are all the ones present in the following files:
  - https://github.com/xmos/lib_dsp/blob/feature/math-xs3/lib_dsp/api/dsp_dot_xs3.h
  - https://github.com/xmos/lib_dsp/blob/feature/math-xs3/lib_dsp/api/dsp_fft_xs3.h
and the two functions:
  - https://github.com/xmos/lib_dsp/blob/feature/math-xs3/lib_dsp/api/dsp_bfp.h#L313
  - https://github.com/xmos/lib_dsp/blob/feature/math-xs3/lib_dsp/api/dsp_bfp.h#L325

The work on this part of the code is still ongoing. The documentation must be completed and more functions may be added in the future.

As a first step, would it be possible to have an estimate of how much time porting the functions above to lib_xs3_math would take?

**Comment by keithm-xmos** [comment]
@lucianomartin and @mbanth, can you review what @astewart-xmos implemented here to ensure it satisfies the request?  If it does then we will try to get this enhancement merged ASAP.

**Comment by mbanth** [comment]
I have compared the descriptions given here by @astewart-xmos to the functions in lib_dsp given by @lucianomartin.  At that level, it all looks good.  I have not tried to review the code changes in Pull Request #95.

I have one minor question mostly out of curiosity, what happens if `xs3_vect_f32_fft_forward( )` receives an odd `fft_length`?

**Comment by lucianomartin** [comment]
I second the comment by @mbanth. The descriptions look like what we wanted, but I haven't looked at the code. Hopefully we will be able to test the upcoming version of lib_xs3_math soon and we will be able to give more feedback.
