### ISSUE TITLE
Build warnings when using x86 clang

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_xs3_math#90]
Looks like an easy fix. No errors, just mildly annoying warnings. We are starting to use clangtidy for linting our code. It's pretty hot on stuff like this.

../../../../build/avona_deps/lib_xs3_math//lib_xs3_math/api/xs3_util.h: In function ‘cls’:
../../../../build/avona_deps/lib_xs3_math//lib_xs3_math/api/xs3_util.h:238:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if((a | mask) != a) return 31-i;
                           ^~
../../../../build/avona_deps/lib_xs3_math//lib_xs3_math/api/xs3_util.h: In function ‘n_bitrev’:
../../../../build/avona_deps/lib_xs3_math//lib_xs3_math/api/xs3_util.h:262:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i = 0; i < bits; i++, dex >>= 1){

**Comment by astewart-xmos** [comment]
I am unable to reproduce the particular warnings above. Attempted using clang and clang-tidy version 6.0.0 on Ubuntu via WSL.

I don't get any warnings at all when compiling with clang without clang-tidy.  With clang-tidy I get about 2000 warnings. Most of them (about 1200) are `warning: use of a signed integer operand with a binary bitwise operator [hicpp-signed-bitwise]`. 
Oddly, though, neither of the warnings you mention are emitted.

So, I'm not really sure what to do here. If I could reproduce those particular warnings, I'd eliminate them. But as it is, clang-tidy emits way too many warnings to deal with.

Thoughts, @ed-xmos?

**Comment by ed-xmos** [comment]
Since this cannot be reproduced and it is a warning only, happy for it to be closed
