### ISSUE TITLE
32 bit shift behaviour is not defined in c99

### ISSUE THREAD

**Issue by uvvpavel** [xmos/lib_xs3_math#97]
After doing some tests I've noticed that when I use bfp_s32_add_scalar to add a very small constant the whole array overflows cause the constant is not being shifted correctly by both gcc and xcc. I think it should have a check like (if (shr >= 32) mant = 0;) to work around the undefined compiler behaviour. This may be the general thing but I think that it's most likely to occur in these types of functions (bfp_s32/s16_add_scalar, bfp_complex_s32/s16_add_scalar) since we use them to add a very small constant before inverting bfp arrays.

P.S. xcore assembly ASHR handles it well, ASHRI doesn't.

**Comment by astewart-xmos** [comment]
I was not able to reproduce any issues regarding this. Nevertheless, I did change the BFP code to handle arithmetic shifts in a safer way.
